name: Cypress Tests
on: [deployment_status]

jobs:
  cypress:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          env: CYPRESS_baseUrl=${{ github.event.deployment_status.target_url }}
