name: Cypress
on: [deployment_status]

jobs:
  cypress:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – web-reader'
    runs-on: ubuntu-20.04
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm i cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          config: baseUrl=${{ github.event.deployment_status.target_url }}
